# Generated by Django 6.0.6 on 2026-06-05 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي'),
        ),
        migrations.AddField(
            model_name='employer',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للتواصل'),
        ),
        migrations.AddField(
            model_name='employer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='employer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='employer',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم المختصر'),
        ),
        migrations.AddField(
            model_name='employer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='employer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='employer',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.TextField(verbose_name='نبذة عن الشركة'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employee_count',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 موظف'), ('11-50', '11-50 موظف'), ('51-200', '51-200 موظف'), ('201-500', '201-500 موظف'), ('501-1000', '501-1000 موظف'), ('1000+', 'أكثر من 1000 موظف')], max_length=20, null=True, verbose_name='عدد الموظفين'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة التأسيس'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='headquarters',
            field=models.CharField(max_length=200, verbose_name='المقر الرئيسي'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(choices=[('tech', 'تقنية المعلومات'), ('construction', 'مقاولات وإنشاءات'), ('medical', 'طبي وصحي'), ('education', 'تعليم وتدريب'), ('marketing', 'تسويق وإعلان'), ('finance', 'مالي ومصارف'), ('consulting', 'استشارات'), ('real_estate', 'عقارات'), ('transport', 'نقل وخدمات لوجستية'), ('hospitality', 'ضيافة وسياحة'), ('oil_gas', 'نفط وغاز'), ('telecom', 'اتصالات'), ('other', 'أخرى')], max_length=50, verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='حساب موثق'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.CreateModel(
            name='EmployerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_registration_file', models.FileField(upload_to='verifications/', verbose_name='السجل التجاري')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='verifications/', verbose_name='شهادة الضريبة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تم القبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='employers.employer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
