# Generated by Django 6.0.6 on 2026-06-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_address_employer_cover_image_employer_email_and_more'),
        ('graduates', '0003_remove_academicproject_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employers.employer')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.graduate')),
            ],
            options={
                'unique_together': {('employer', 'graduate')},
            },
        ),
    ]
