# Generated by Django 6.0.6 on 2026-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='employer_notes',
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='المزايا'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'مبتدئ (0-2 سنوات)'), ('junior', 'Junior (2-4 سنوات)'), ('mid', 'متوسط (4-7 سنوات)'), ('senior', 'Senior (7-10 سنوات)'), ('expert', 'خبير (10+ سنوات)')], default='entry', max_length=20, verbose_name='مستوى الخبرة'),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills',
            field=models.TextField(blank=True, null=True, verbose_name='المهارات المفضلة'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='المسؤوليات'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة تعريفية'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب المتوقع'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المقابلة'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات صاحب العمل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(verbose_name='آخر موعد للتقديم'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='الوصف الوظيفي'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='تم شغلها'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False, verbose_name='الراتب قابل للتفاوض'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('remote', 'عن بعد'), ('hybrid', 'هجين (حضوري وعن بعد)'), ('internship', 'تدريب'), ('contract', 'عقد مؤقت')], max_length=20, verbose_name='نوع الوظيفة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(verbose_name='المهارات المطلوبة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للراتب'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للراتب'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('interview', 'مقابلة'), ('accepted', 'قبول مبدئي'), ('rejected', 'رفض'), ('hired', 'تم التعيين')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
