# Generated by Django 6.0.6 on 2026-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_employer_notes_job_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='بث مباشر'),
        ),
        migrations.AddField(
            model_name='job',
            name='live_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط البث المباشر'),
        ),
    ]
