# Generated by Django 6.0.6 on 2026-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('keywords', models.CharField(blank=True, help_text='مفصولة بفاصلة', max_length=200, verbose_name='كلمات مفتاحية')),
            ],
        ),
    ]
