# Generated by Django 6.0.6 on 2026-06-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0003_companyreview'),
        ('graduates', '0003_remove_academicproject_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التخصص')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز التخصص')),
                ('department', models.CharField(max_length=100, verbose_name='القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المهارة')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(choices=[('super_admin', 'مدير النظام'), ('alumni_manager', 'مدير شؤون الخريجين'), ('academic_admin', 'مشرف أكاديمي'), ('content_moderator', 'مشرف محتوى'), ('report_viewer', 'مدير تقارير')], max_length=30, verbose_name='مستوى المشرف')),
                ('permissions', models.JSONField(default=dict, verbose_name='صلاحيات إضافية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('approve', 'موافقة'), ('reject', 'رفض'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('export', 'تصدير')], max_length=30, verbose_name='الإجراء')),
                ('target_type', models.CharField(max_length=50, verbose_name='نوع المستهدف')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='معرف المستهدف')),
                ('details', models.JSONField(default=dict, verbose_name='تفاصيل إضافية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='الكلمة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_registration_file', models.FileField(upload_to='verifications/employers/', verbose_name='السجل التجاري')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='verifications/employers/', verbose_name='شهادة الضريبة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تم القبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_verification_requests', to='employers.employer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفعالية')),
                ('event_type', models.CharField(choices=[('job_fair', 'ملتقى توظيف'), ('workshop', 'ورشة عمل'), ('seminar', 'ندوة'), ('graduation', 'حفل تخرج'), ('training', 'دورة تدريبية')], max_length=30, verbose_name='نوع الفعالية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateTimeField(verbose_name='تاريخ الفعالية')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='رابط الفعالية الافتراضية')),
                ('max_attendees', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للحضور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='صورة الفعالية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('employment', 'تقرير التوظيف'), ('skill_gap', 'تقرير فجوات المهارات'), ('satisfaction', 'تقرير رضا الخريجين'), ('survey_performance', 'تقرير أداء الاستبيانات'), ('company_activity', 'تقرير نشاط الشركات'), ('system_health', 'تقرير سير النظام')], max_length=30, verbose_name='نوع التقرير')),
                ('parameters', models.JSONField(default=dict, verbose_name='معاملات التقرير')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='ملف التقرير')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='مجدول')),
                ('scheduled_recipient', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد المستلم للتقرير المجدول')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاستبيان')),
                ('timing', models.CharField(choices=[('upon_graduation', 'عند التخرج'), ('after_6_months', 'بعد 6 أشهر'), ('after_12_months', 'بعد 12 شهر'), ('after_18_months', 'بعد 18 شهر')], max_length=30, verbose_name='التوقيت')),
                ('questions', models.JSONField(verbose_name='الأسئلة')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال المجدول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('general', 'إعدادات عامة'), ('registration', 'إعدادات التسجيل'), ('verification', 'إعدادات التوثيق'), ('notification', 'إعدادات الإشعارات'), ('privacy', 'إعدادات الخصوصية')], max_length=30, verbose_name='نوع الإعداد')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_university_number', models.CharField(max_length=20, verbose_name='الرقم الجامعي')),
                ('uploaded_document', models.FileField(upload_to='verifications/graduates/', verbose_name='الوثيقة المرفقة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تم القبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='graduates.graduate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='dashboard.event')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.graduate')),
            ],
            options={
                'unique_together': {('event', 'graduate')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='الإجابات')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduates.graduate')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('survey', 'graduate')},
            },
        ),
    ]
