# Generated by Django 6.0.6 on 2026-06-10 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notification'),
        ('employers', '0003_companyreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='successstory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successstory',
            name='author_type',
            field=models.CharField(choices=[('graduate', 'خريج'), ('company', 'شركة')], default='graduate', max_length=20),
        ),
        migrations.AddField(
            model_name='successstory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='employers.employer'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successstory',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'منشور'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='successstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
