# Generated by Django 6.0.6 on 2026-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_successstory_options_successstory_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_graduate', 'خريج جديد'), ('new_job', 'وظيفة جديدة'), ('verification_approved', 'تم قبول التوثيق'), ('verification_rejected', 'تم رفض التوثيق'), ('welcome', 'ترحيب'), ('info', 'معلومات'), ('success', 'نجاح'), ('danger', 'تحذير'), ('system', 'إشعار نظام')], max_length=30),
        ),
    ]
