# Generated by Django 6.0.6 on 2026-06-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='تم النشر'),
        ),
        migrations.AddField(
            model_name='survey',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
    ]
