# Generated by Django 6.0.6 on 2026-07-11 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='تم تأكيد البريد الإلكتروني'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('attempts', models.IntegerField(default=0, verbose_name='عدد محاولات الفشل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'التحقق من البريد الإلكتروني',
                'verbose_name_plural': 'التحقق من البريد الإلكتروني',
                'ordering': ['-created_at'],
            },
        ),
    ]
