# Generated by Django 6.0.6 on 2026-06-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduates', '0003_remove_academicproject_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاستبيان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('timing', models.CharField(choices=[('upon_graduation', 'عند التخرج'), ('after_6_months', 'بعد 6 أشهر'), ('after_12_months', 'بعد 12 شهر'), ('after_18_months', 'بعد 18 شهر')], max_length=30, verbose_name='التوقيت')),
                ('questions', models.JSONField(verbose_name='الأسئلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='الإجابات')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='graduates.graduate')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'graduate')},
            },
        ),
    ]
