# Generated by Django 6.0.6 on 2026-06-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبولة'), ('rejected', 'مرفوضة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم المجموعة'),
        ),
    ]
