# Generated by Django 6.0.6 on 2026-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_callroom_roomparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AddField(
            model_name='callroom',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='الإعجابات'),
        ),
        migrations.AddField(
            model_name='callroom',
            name='room_type',
            field=models.CharField(choices=[('video', '🎥 مكالمة فيديو'), ('audio', '🎧 مكالمة صوتية'), ('live', '📺 بث مباشر')], default='video', max_length=20, verbose_name='نوع الغرفة'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='منشئ الغرفة'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='متصل'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='peer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peer ID'),
        ),
        migrations.AlterField(
            model_name='callroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'في انتظار المشاركين'), ('active', 'جارية'), ('ended', 'انتهت')], default='waiting', max_length=20, verbose_name='الحالة'),
        ),
    ]
