# Generated by Django 6.0.6 on 2026-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_graduate_reward_points_alter_graduate_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_file',
        ),
        migrations.AlterField(
            model_name='graduate',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المعدل التراكمي'),
        ),
    ]
