# Generated by Django 6.0.6 on 2026-06-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_graduate_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
