# Generated by Django 6.0.6 on 2026-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_graduate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='receive_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='receive_sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
