# Generated by Django 6.0.6 on 2026-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_workexperience_email_workexperience_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='receive_sms_notifications',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, verbose_name='استقبال إشعارات عبر البريد الإلكتروني'),
        ),
    ]
