# Generated by Django 6.0.6 on 2026-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0007_remove_workexperience_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='receive_email_notifications',
        ),
        migrations.AddField(
            model_name='graduate',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, verbose_name='استقبال إشعارات البريد الإلكتروني'),
        ),
    ]
